version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: sqlite3
    versions:
    - ">= 1.4.a, < 1.5"
  rebase-strategy: disabled
