require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - spec/dummy/db/schema.rb
    - bin/rake

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/MixinUsage:
  Exclude:
    - spec/dummy/bin/*

Style/Documentation:
  Enabled: false

Rails:
  Enabled: true

Rails/FilePath:
  EnforcedStyle: slashes

Rails/ApplicationRecord:
  Enabled: false

Style/Lambda:
  Enabled: false
